Convert latlon type
geolonia/geolonia-locations-action pull request #23
Opened 2022-11-14 08:58 UTC by naogify

2022-11-15 00:39 UTC, keichan34 requested changes
確認お願いします

2022-11-15 00:39 UTC, keichan34 commented on entrypoint.sh
> +  sed -i -e "s/['\"]//g" $FILE
これやめましょう。 single quote を使って文字列を区切るのはJSONとしてダメなので、それをエラーにすべきかと思う

2022-11-15 00:39 UTC, keichan34 commented on bin/convertToNumber.js
> +  process.stdout.write(targetFile);
これ不要かと？ファイルパスを出力する必要ありますか？

2022-11-15 00:53 UTC, naogify commented on entrypoint.sh
> +  sed -i -e "s/['\"]//g" $FILE
これはCSV限定の処理で、
緯度経度の値が single quote で囲まれているケースもあり得るかなと思ったのですが、どうでしょうか？

2022-11-15 00:57 UTC, keichan34 commented on entrypoint.sh
> +  sed -i -e "s/['\"]//g" $FILE
いやー、無差別に削除すると逆に崩れる可能性が高いと思う。。ちゃんとCSVをパースして削除したりするのべつだけど。。

2022-11-15 00:59 UTC, naogify commented on bin/convertToNumber.js
> +  process.stdout.write(targetFile);
シェルスクリプト側で出力したファイルパスが欲しかったので、標準出力に書き込んだのですが、

例えば、フォーマットした GeoJSONで上書きした方が簡潔で良いかもしれないですね、、🤔

2022-11-15 01:01 UTC, naogify commented on entrypoint.sh
> +  sed -i -e "s/['\"]//g" $FILE
あ、、確かに、double quote で囲まれている 改行入ってる値があると、崩れるかもしれないです。
CSV を nodejs でパースして、緯度経度の値のみ、数値に変換する方が良いですね、、、

2022-11-15 02:00 UTC, naogify commented on entrypoint.sh
> +  sed -i -e "s/['\"]//g" $FILE
こちら処理を削除しました。確認お願いします。

2022-11-15 02:00 UTC, naogify commented on bin/convertToNumber.js
> +  process.stdout.write(targetFile);
こちら既存の GeoJSON を上書きするように修正しました。お手すきの時に確認お願いします!

2022-11-16 01:12 UTC, keichan34 approved these changes

2022-11-16 01:59 UTC, keichan34 approved these changes

2022-11-16 01:59 UTC, merged